apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testgo123
  janus-idp.io/tekton: testgo123
  backstage.io/kubernetes-id: testgo123
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testgo123
resources: 
- deployment.yaml
- route.yaml
- service.yaml
